CREATE SCHEMA IF NOT EXISTS `lmjfdb` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE IF NOT EXISTS `lmjfdb`.`anneeScolaire` (
    `academicYear` VARCHAR(45) NOT NULL,
    `created_at` TIMESTAMP NOT NULL,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`AcademicYear`)
)  ENGINE=INNODB DEFAULT CHARACTER SET=UTF8;

CREATE TABLE IF NOT EXISTS `lmjfdb`.`ProfPrincipal` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `idTeacher` INT(11)  NULL,
    `classRoomID` INT(11)  NULL,
    `created_at` TIMESTAMP  NULL,
    `updated_at` TIMESTAMP  NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARACTER SET=UTF8;

CREATE TABLE IF NOT EXISTS `lmjfdb`.`Cycle` (
    `cycleID` INT(11) NOT NULL AUTO_INCREMENT,
    `cycleName` VARCHAR(45) NULL DEFAULT NULL,
    `typeCycle` VARCHAR(45) NULL DEFAULT NULL,
    `cycleDescription` VARCHAR(45) NULL DEFAULT NULL,
    `created_at` TIMESTAMP NOT NULL,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`cycleID`)
)  ENGINE=INNODB DEFAULT CHARACTER SET=UTF8;

CREATE TABLE IF NOT EXISTS `lmjfdb`.`Course` (
    `courseID` INT(11) NOT NULL AUTO_INCREMENT,
    `cycleID` INT(11) NULL,
    `courseName` VARCHAR(45) NULL DEFAULT NULL,
    `courseDescription` VARCHAR(45) NULL DEFAULT NULL,
    `courseCoeff` VARCHAR(45) NOT NULL,
    `created_at` TIMESTAMP NOT NULL,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`courseID`)
)  ENGINE=INNODB DEFAULT CHARACTER SET=UTF8;

CREATE TABLE IF NOT EXISTS `lmjfdb`.`CourseChild` (
    `CourseChildID` INT(11) NOT NULL AUTO_INCREMENT,
    `courseID` INT(11) NOT NULL,
    `labelCourse` VARCHAR(45) NULL DEFAULT NULL,
    `created_at` TIMESTAMP NOT NULL,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`CourseChildID`)
)  ENGINE=INNODB DEFAULT CHARACTER SET=UTF8;

CREATE TABLE IF NOT EXISTS `lmjfdb`.`courseTest` (
    `CoursetestID` INT(11) NOT NULL AUTO_INCREMENT,
    `semestreID` INT(11)  NULL,
    `CourseChildID` INT(11)  NULL,
    `teacherID` INT(11)  NULL,
    `classRoomID` INT(11)  NULL,
    `testName` VARCHAR(45) NULL DEFAULT NULL,
    `testDescription` VARCHAR(45) NULL DEFAULT NULL,
    `maxGradevalue` VARCHAR(45) NULL DEFAULT NULL,
    `created_at` TIMESTAMP NOT NULL,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`CoursetestID`)

)  ENGINE=INNODB DEFAULT CHARACTER SET=UTF8;

-- notes d'evaluation

CREATE TABLE IF NOT EXISTS `lmjfdb`.`courseGrade` (
    `studentMatricule` INT(11) NOT NULL,
    `semestreID` INT(11) NOT NULL,
    `testID` INT(11)  NULL,
    `Grade` VARCHAR(45) NULL DEFAULT NULL,
    `Appreciation` VARCHAR(45) NULL DEFAULT NULL,
    `created_at` TIMESTAMP  NULL,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`studentMatricule` , `semestreID` , `testID`)
)  ENGINE=INNODB DEFAULT CHARACTER SET=UTF8;
--
--
-- --- moyenne semestrielle
CREATE TABLE IF NOT EXISTS `lmjfdb`.`AverageGrade` (
    `studentMatricule` INT(11) NOT NULL,
    `semestreID` INT(11) NOT NULL,
    `comitteeAppreciation` VARCHAR(45) NULL DEFAULT NULL,
    `position` VARCHAR(45) NULL DEFAULT NULL,
    `NbrStudent` VARCHAR(45) NULL DEFAULT NULL,
    `created_at` TIMESTAMP NOT NULL,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`studentMatricule` , `semestreID`)
)  ENGINE=INNODB DEFAULT CHARACTER SET=UTF8;



CREATE TABLE IF NOT EXISTS `lmjfdb`.`Classroom` (
    `classRoomID` INT(11) NOT NULL AUTO_INCREMENT,
    `classRomLocationName` VARCHAR(45) NULL DEFAULT NULL,
    `typeClassRoom` VARCHAR(45) NULL DEFAULT NULL,
    `BuildingLevel` VARCHAR(45) NULL DEFAULT NULL,
    `ClassRoomName` VARCHAR(45) NULL DEFAULT NULL,
    `ClassRoomDescription` VARCHAR(45) NULL DEFAULT NULL,
    `created_at` TIMESTAMP NOT NULL,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`classRoomID`)
)  ENGINE=INNODB DEFAULT CHARACTER SET=UTF8;

CREATE TABLE IF NOT EXISTS `lmjfdb`.`Enrollment` (
    `academicYear` VARCHAR(45) NOT NULL,
    `classRoomID` INT(11) NOT NULL,
    `created_at` TIMESTAMP NOT NULL,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`academicYear` , `classRoomID`)
)  ENGINE=INNODB DEFAULT CHARACTER SET=UTF8;

CREATE TABLE IF NOT EXISTS `lmjfdb`.`Student` (
    `studentMatricule` VARCHAR(45) NOT NULL,
    `classRoomID` INT(11)  NULL,
    `studentParentID` INT(11)  NULL,
    `studentName` VARCHAR(255)  NULL,
    `studentLastName` VARCHAR(255)  NULL,
    `studentBirthdate` VARCHAR(45)  NULL,
    `studentSexe` VARCHAR(1)  NULL,
    `studentBirthPlace` VARCHAR(225) NULL DEFAULT NULL,
    `responsableStudent` VARCHAR(45)  NULL,
    `contactresponsableStudent` VARCHAR(45) NOT NULL,
    `studentRegime` VARCHAR(45) NULL,
    `studentInterne` VARCHAR(45) NULL,
    `studentAffecte` VARCHAR(45) NULL,
    `studentRedoublant` BOOLEAN DEFAULT FALSE,
    `created_at` TIMESTAMP NOT NULL,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`studentMatricule`)
)  ENGINE=INNODB DEFAULT CHARACTER SET=UTF8;

CREATE TABLE IF NOT EXISTS `lmjfdb`.`Parent` (
    `parentID` INT(11) NOT NULL AUTO_INCREMENT,
    `parentFistName` VARCHAR(45) NULL DEFAULT NULL,
    `parentLastName` VARCHAR(255) NULL DEFAULT NULL,
    `parentPassword` VARCHAR(45) NULL DEFAULT NULL,
    `parentTelephone` VARCHAR(45) NULL DEFAULT NULL,
    `created_at` TIMESTAMP NOT NULL,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`parentID`)
)  ENGINE=INNODB DEFAULT CHARACTER SET=UTF8;


CREATE TABLE IF NOT EXISTS `lmjfdb`.`Semestre` (
    `semestreID` INT(11) NOT NULL AUTO_INCREMENT,
    `semestreDescription` VARCHAR(45) NULL DEFAULT NULL,
    `academicYear` VARCHAR(45) NOT NULL,
    `startDate` VARCHAR(45) NOT NULL,
    `endDate` VARCHAR(45) NOT NULL,
    `created_at` TIMESTAMP NOT NULL,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`semestreID`)
)  ENGINE=INNODB DEFAULT CHARACTER SET=UTF8;

CREATE TABLE IF NOT EXISTS `lmjfdb`.`Teacher` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `idTeacher` INT(11) NOT NULL ,
    `courseID` INT(11) NOT NULL,
    `classRoomID` INT(11) NULL,
    `created_at` TIMESTAMP NOT NULL,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
)  ENGINE=INNODB DEFAULT CHARACTER SET=UTF8;


CREATE TABLE IF NOT EXISTS `lmjfdb`.`Time_period` (
    `TimePeriodID` INT(11) NOT NULL AUTO_INCREMENT,
    `StartHour` VARCHAR(45) NULL DEFAULT NULL,
    `EndHour` VARCHAR(45) NULL DEFAULT NULL,
    `DayOFWeek` VARCHAR(45) NULL DEFAULT NULL,
    `created_at` TIMESTAMP NOT NULL,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`TimePeriodID`)
)  ENGINE=INNODB DEFAULT CHARACTER SET=UTF8;

CREATE TABLE IF NOT EXISTS `lmjfdb`.`CourseSchedule` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
    `CourseID` INT(11) NOT NULL,
    `TimePeriodID` INT(11) NOT NULL,
    `ClassRoomID` INT(11) NOT NULL,
    `TeacherID` INT(11) NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`Id`)
)  ENGINE=INNODB DEFAULT CHARACTER SET=UTF8;

CREATE TABLE IF NOT EXISTS `lmjfdb`.`Absence` (
    `studentMatricule` VARCHAR(45) NOT NULL,
    `TimePeriodID` INT(11) NOT NULL,
    `Date` VARCHAR(45) NULL DEFAULT NULL,
    `created_at` TIMESTAMP NOT NULL,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`studentMatricule` , `TimePeriodID`)
)  ENGINE=INNODB DEFAULT CHARACTER SET=UTF8;

CREATE TABLE IF NOT EXISTS `lmjfdb`.`Retard` (
    `studentMatricule` VARCHAR(45) NOT NULL,
    `TimePeriodID` INT(11) NOT NULL,
    `Date` VARCHAR(45) NULL DEFAULT NULL,
    `created_at` TIMESTAMP NOT NULL,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`studentMatricule` , `TimePeriodID`)
)  ENGINE=INNODB DEFAULT CHARACTER SET=UTF8;




-- CREATE TABLE IF NOT EXISTS `lmjfdb`.`Student` (
--   `studentID` INT(11) NOT NULL AUTO_INCREMENT,
--   `classRoomID` INT(11) NOT NULL ,
--   `academicYear`VARCHAR(45) NOT NULL,
--   `studentName` VARCHAR(45) NOT NULL,
--   `studentLastName` VARCHAR(45) NULL DEFAULT NULL,
--   `studentBirthdate` VARCHAR(45) NULL DEFAULT NULL,
--   `responsableStudent` VARCHAR(45) NOT NULL,
--   `contactresponsableStudent` VARCHAR(45) NOT NULL,
--   `studentStatus` VARCHAR(45) NULL,
--   `studentDoublant`  BOOLEAN DEFAULT FALSE,
--   `created_at` TIMESTAMP NOT NULL,
--   `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
--   PRIMARY KEY (`studentID`),
--   INDEX `r_studentID_idx` (`studentID` ASC),
--   CONSTRAINT `e_AcademicYearID`
--     FOREIGN KEY (`academicYear`)
--     REFERENCES `lmjfdb`.`anneeScolaire` (`academicYear`)
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION,
--   CONSTRAINT `e_classRoomID`
--       FOREIGN KEY (`classRoomID`)
--       REFERENCES `lmjfdb`.`Classroom` (`classRoomID`)
--       ON DELETE NO ACTION
--       ON UPDATE NO ACTION
-- )
-- ENGINE = InnoDB
-- DEFAULT CHARACTER SET = utf8;
